version: "1"

capabilities:
  - contract_id: "abesh:httpserver"
    values:
      host: "0.0.0.0"
      port: "8080"
      default_request_timeout: "5s"

  - contract_id: "abesh:ex_echo"
    values:
      encoding_name: "json"

triggers:
  - trigger: "abesh:httpserver"
    trigger_values:
      method: "GET"
      path: "/json"
    service: "abesh:ex_echo"

start:
  - "abesh:httpserver"
