name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run tests and collect coverage
        run: go test ./... -coverprofile=cover.out -v

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
